import type {Metadata} from 'next'
import './globals.css'
import {AppRouterCacheProvider} from '@mui/material-nextjs/v14-appRouter';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <meta name="viewport" content="initial-scale=1, width=device-width"/>
            <title>Shopgaper</title>
        </head>
        <body>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </body>
        </html>
    )
}
